version: '3.4'
networks:
  host-exposed:
    driver: bridge
  inside:
    internal: true

services:
  autoheal:
    container_name: neo-local_autoheal
    depends_on:
      - neo-faucet
      - neo-cli-privatenet-1
      - neo-python
      - neo-scan
      - postgres
    environment:
      - AUTOHEAL_CONTAINER_LABEL=autoheal
      - AUTOHEAL_INTERVAL=5
      - DOCKER_SOCK=/var/run/docker.sock
    image: willfarrell/autoheal
    networks:
      - inside
    restart: always
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'

  neo-cli-privatenet-1:
    container_name: neo-cli-privatenet-1
    environment:
      NODE_NUMBER: 1
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 60s
      test:
        - CMD
        - bash
        - '-c'
        - /opt/healthcheck-node.sh
      timeout: 10s
    image: 'cityofzion/neo-local-privatenet:$NODE1_NEO_CLI_VERSION$BOOTSTRAP'
    networks:
      - inside
      - host-exposed
    labels:
      autoheal: 'true'
    ports:
      - '20333:20333'
      - '30333:30333'
    restart: always

  neo-faucet:
    container_name: neo-faucet
    depends_on:
      - neo-scan
    environment:
      NEOSCAN: 'neo-scan:4000'
      MIN_BLOCK: '1000'
      GAS_REWARD: '1000s'
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 20s
      test:
        - CMD
        - bash
        - '-c'
        - exec 6<>/dev/tcp/127.0.0.1/4002
      timeout: 10s
    image: 'cityofzion/neo-local-faucet:latest'
    labels:
      autoheal: 'true'
    links:
      - 'neo-scan:4000'
    networks:
      - inside
      - host-exposed
    ports:
      - '4002:4002'
    volumes:
      - >-
        ./container-override-files/neo-faucet/protocol.json:/usr/src/app/assets/protocol.json
    restart: always

  neo-python:
    container_name: neo-python
    depends_on:
      - neo-cli-privatenet-1
      - neo-scan
    image: 'cityofzion/neo-python:v0.8.4'
    networks:
      - inside
      - host-exposed
    tty: true
    volumes:
      - './smart-contracts:/smart-contracts'
      - './wallets:/wallets'
      - >-
        ./container-override-files/neo-python/protocol.privnet.json:/neo-python/neo/data/protocol.privnet.json

  neo-scan:
    container_name: neo-scan
    depends_on:
      - postgres
      - neo-cli-privatenet-1
    environment:
      DB_DATABASE: neoscan_prodv
      DB_HOSTNAME: postgres
      DB_PASSWORD: postgres
      DB_USERNAME: postgres
      NEO_SEEDS: >-
        http://neo-cli-privatenet-1:30333
      PORT: 4000
      REPLACE_OS_VARS: 'true'
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 20s
      test:
        - CMD
        - bash
        - '-c'
        - exec 6<>/dev/tcp/127.0.0.1/4000
      timeout: 10s
    image: 'cityofzion/neoscan:latest'
    labels:
      autoheal: 'true'
    links:
      - 'neo-cli-privatenet-1:30333'
    networks:
      - inside
      - host-exposed
    ports:
      - '4000:4000'
    restart: always

  postgres:
    container_name: postgres
    environment:
      POSTGRES_DB: neoscan_prodv
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    expose:
      - 5432
    image: 'library/postgres:12-alpine'
    networks:
      - inside
    restart: always
